### ISSUE TITLE
Cloud build failed

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/sidekick-feedback#16] opened 2017-08-02 07:15 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Intercom message:  I've tried a couple of iOS cloud builds (from a Win10 machine). It failed both times. The last message was:

```
[17-08-02 14:18:42.634] (Info) Prepare Project for Platform - ios
[17-08-02 14:18:42.635] (Info) sandbox-exec: /tmp/builds/_/cea470a6fba1c7e46117477817dfe2378cc0b81b/weighing/rule.sb: No such file or directory
[17-08-02 14:18:42.635] (Info) sandbox-exec: /tmp/builds/_/cea470a6fba1c7e46117477817dfe2378cc0b81b/weighing/rule.sb: No such file or directory
[17-08-02 14:18:52.336] (Error) ab.buildDeploy.shell.build - Build failed.
DEVICES 1 OUTPUT 1
```

### Which platform(s) does the issue occur on?
iOS
Windows 10

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by stoskov** [comment] 2017-08-03 11:34
Please provide us more information. Does it happen every time and is it still reproducible? Providing the project might help.

**Comment by LeopoldPodmolik** [comment] 2017-08-05 14:54
I try cloud iOS build from ubuntu 16.04 ... just set provising and certificate file and push build .... in log console see` (Info) Build started. ` and that is all ... where can be problem ? ... any errors ... nothing

**Comment by two-bridges** [comment] 2017-08-08 03:10
**Version Numbers**
- NativeScript Sidekick: Version: 0.2.0-v.2017.7.31.4 (latest)
- NativeScript CLI: 3.1.3
- CLI extension nativescript-cloud: 0.11.6
- CLI extension nativescript-starter-kits: 0.1.11

Check for updates

**Tell us how to recreate the issue in as much detail as possible.**
1. Started a new tns project on mac.  Using --ng.  
2. Built and run the project on mac, testing in simulator and on iPad.  it's working fine
3. checked in to git on mac
4. pulled git to windows 10 PC
5. did npm install to load from packages.json (they're not in git)
6. plug in iPad, setup provisioning and certificate (copied from mac)
7. loaded the project into Sidekick.  Selected Run -> Run on Device
8. build starts.. takes 4-5 minutes (same as mac pretty much, which is a old slow mac)
9. build fails, as per the logs

**Same issue happens everytime?**
Yes.  When 'Run on Device' always fails to build.  
Note: Run -> Build works.  Ie. a normal build will work, but 'Run on Device' results in 'Build Failed'

**Logs:**
[gist containing logs:](https://gist.github.com/two-bridges/af1b9089d34fea4f42ab3ce4f49f3765)

**Comment by tsvetie** [comment] 2017-08-16 09:02
@LeopoldPodmolik Can you send us the log files situated in _~/.config/NativeScriptSidekick/Logs_? Additionally, can you reproduce the problem consistently? This sounds like a different problem than the one reported originally.

@two-bridges We will look into the log files.

**Comment by ShyshkovOleg** [comment] 2018-03-02 11:38
I have the same issue as two-bridges. Did anyone solve this ?

**Comment by two-bridges** [comment] 2018-03-04 21:45
@ShyshkovOleg, I could not get SideKick to work for my project.  It's uses a few plugins, some with pod dependencies (you know, the ios specific packages that some plugins require).   

SideKick was much newer then. I will try this again and see if things have improved and report back here...

Theoretically, I can't see why my project can't build.

**Comment by SerhanP** [comment] 2018-06-19 11:09
Having the same issue.

`[18-06-19 13:06:55.892] (CLI)  sandbox-exec: /tmp/builds/_/2fc5d1b4af0493328adc2851bf53e3e5e92a2413/4.0.2/fuhrparknativescript/rule.sb: 
[18-06-19 13:06:55.892] (CLI)  No such file or directory
[18-06-19 13:06:55.892] (CLI) sandbox-exec: /tmp/builds/_/2fc5d1b4af0493328adc2851bf53e3e5e92a2413/4.0.2/fuhrparknativescript/rule.sb: No such file or directory`

**Version numbers**
- Sidekick Version: 1.10.2-v.2018.6.5.2 (latest)
- NativeScript CLI version: 4.1.0
- CLI extension nativescript-cloud version: 1.10.0
- CLI extension nativescript-starter-kits version: 0.3.4

**Comment by ggarabedian** [comment] 2018-06-26 11:56
Hello @SerhanP,

I am not able to reproduce the reported error with a sample app and I will ask you to share additional information so we can investigate this further. Can you please rebuild your app and then share the produced logs here? To access the logs, open Sidekick and select **Help** -> **Show Logs** from the top menu.

**Comment by codealvarez** [comment] 2018-09-05 08:55
Hi, I have the same issue. Do you have some solutions already?

When I'm trying to build in Android is OK, but iOS fails.

Error:
`sandbox-exec: /tmp/builds/_/5ff56895f98d2dfff9d56b0ffde3cd675e6de4f8/4.2.3/YourApp/rule.sb: No such file or directory
`
`Unable to apply changes on device: ee1b9ea449ba85c64e92e4fa9cdedf15cf1032f9. Error is: Build failed..`

**Comment by ShyshkovOleg** [comment] 2018-09-05 12:38
Hi, @codealvarez.
Do you use firebase plugin?

**Comment by codealvarez** [comment] 2018-09-07 19:45
Hi @ShyshkovOleg 

Yes, I’m using it now. That’s the problem?

**Comment by ShyshkovOleg** [comment] 2018-09-10 11:37
Hi, @codealvarez.
That was my case. Note that I used Sidekick to build the app on IOS.
There is NS showCase app by Eddy, opensource. FireBase works there perfectly. Perhaps You could download it an refactor it to you needs.

**Comment by dpdragnev** [comment] 2018-12-19 16:33
I am having the same issue.  I think thread is 2 years old, but did anyone found a fix for this problem?

**Comment by kevin811103** [comment] 2018-12-29 10:34
I also have the same problem

**Comment by kapiltiwari61** [comment] 2019-01-22 14:51
Build failed for android using nativesidekick. Please find the logs.
 ```
Could not resolve all dependencies for configuration ':app:_F0F1F2F3F4F5F6F7F8F9F10DebugApkCopy'.
[19-01-22 20:16:23.285] (CLI)    > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)      Required by:
[19-01-22 20:16:23.285] (CLI)          project :app
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)    > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
[19-01-22 20:16:23.285] (CLI)      Required by:
[19-01-22 20:16:23.285] (CLI)          project :app
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)    > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)      Required by:
[19-01-22 20:16:23.285] (CLI)          project :app
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'.
[19-01-22 20:16:23.285] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.285] (CLI)       > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:2.1.
[19-01-22 20:16:23.285] (CLI)          > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid
[19-01-22 20:16:23.289] (CLI) -util-2.1.pom'.
[19-01-22 20:16:23.289] (CLI)             > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/2.1/mobilemind-droid-util-2.1.pom'. Received status code 502 from server: Bad Gateway
[19-01-22 20:16:23.289] (CLI) * Try:
[19-01-22 20:16:23.289] (CLI) Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[19-01-22 20:16:23.289] (CLI) * Get more help at https://help.gradle.org
[19-01-22 20:16:23.289] (CLI) BUILD FAILED in 13s
[19-01-22 20:16:23.289] (CLI) Command ./gradlew failed with exit code 1
[19-01-22 20:16:23.289] (CLI) bc_S4NWswvDOFlQTCssNH
```

**Comment by ggarabedian** [comment] 2019-01-23 11:31
@kapiltiwari61, this issue is related to the [nativescript-background-task](https://github.com/mobilemindtec/nativescript-background-task) plugin and not Sidekick or the NativeScript CLI. It seems that some of the plugin dependencies are downloaded from locations that are down.

Having said that, if you continue to experience this error, I recommend that you contact the plugin developers or submit an issue in their repository.

**Closed** 2020-03-06 20:49 UTC
Labels: bug, need more information
