### ISSUE TITLE
No updated packages

### ISSUE THREAD

**Issue by Izrab** [NativeScript/sidekick-feedback#409] opened 2019-07-29 08:57 UTC
### Did you verify whether this issue has already been reported here?
No_

### Tell us about the problem
When I want to install plugins, Sidekick is unaware of the new updates of the packages, like `tns-platform-declaration`, it gives old version number and says it is the latest version. 
![Annotation 2019-07-29 115137](https://user-images.githubusercontent.com/22328131/62035180-2846eb00-b1a4-11e9-906f-a3a539a60b0b.png)
![Annotation 2019-07-29 115215](https://user-images.githubusercontent.com/22328131/62035184-2aa94500-b1a4-11e9-9790-d7cf52696c66.png)

### Which platform(s) does the issue occur on?
_Windows 10

### Provide the following version numbers that the issue occurs with:
![Annotation 2019-07-29 115516](https://user-images.githubusercontent.com/22328131/62035195-2ed56280-b1a4-11e9-81a8-5875027dc145.png)

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:**

**Comment by tsonevn** [comment] 2019-08-01 09:27
Duplicate of #408

**Closed by tsonevn** 2019-08-01 09:27 UTC
Labels: bug
