### ISSUE TITLE
"Error: Couldn't find package.json data in installed template" when creating projects.

### ISSUE THREAD

**Issue by PaulHalliday** [NativeScript/sidekick-feedback#23] opened 2017-08-05 15:47 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I've downloaded and installed the NativeScript Sidekick. Upon attempting to make a project with _any_ template, I get the following error:

[17-08-05 16:39:38.662] (Error) ab.createApp.shell.create - **Couldn't find package.json data in installed template**

### Which platform(s) does the issue occur on?
macOS. Errors with both npm@5 && npm@4.

### Provide the following version numbers that the issue occurs with:

Version: 0.2.0-v.2017.7.31.4 (latest)
NativeScript CLI version: 8.1.2
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Select + Create
3. Select a template, directory and application name.
4. Click "Create App"

### Does this issue happen every time?
Yes

### Send the client logs.
https://gist.github.com/PaulHalliday/0816c863664faa850da525e951af56f2

### Test with npm@4:
https://gist.github.com/PaulHalliday/edcad9d0ad8576e7857e41111a0b9ac4

**Comment by louiszgm** [comment] 2017-08-07 01:06
I also have the same problem when i am creating the project. Did you work it out?

**Comment by tsvetie** [comment] 2017-08-07 08:50
Hi @PaulHalliday and @louiszgm,

The problem is that you are using an older version of NativeScript CLI. The bug (https://github.com/NativeScript/nativescript-cli/issues/2870) is fixed in the latest version - 3.1.3.

**Comment by louiszgm** [comment] 2017-08-08 09:32
@tsvetie Thanks! It works for me

**Closed** 2017-08-08 14:47 UTC
