### ISSUE TITLE
SASS - CSS compile problems

### ISSUE THREAD

**Issue by truewt** [NativeScript/sidekick-feedback#46] opened 2017-09-08 16:09 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I'm using NativeScript with Angular (+ SASS with NativeScript Theme Light), and I created project with NativeScript Sidekick. I have problems whenever I add some SCSS and "link" for it to the Angular component, because the whole app is without design. This problem happens when new SCSS is added when LiveSync is already running. For complete guide on how to reproduce this error, please see how to recreate issue, described below. If you are also involved into NativeScript development or NativeScript Angular, I would please you to check out this two questions I already wrote before:
- [Replacements and styling for Android/iOS components in NativeScript](https://github.com/NativeScript/NativeScript/issues/4812)
- [Styling of SideDrawer's list items disappear when compiling with AOT](https://github.com/NativeScript/nativescript-angular/issues/984)

### Which platform(s) does the issue occur on?
Mobile: Both Android and iOS - I think it does not depend on mobile OS at all, since it fails in general
Computer: macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 0.2.2-v.2017.8.9.3 (latest)
- **NativeScript CLI:** 3.1.3
- **CLI extension nativescript-cloud:** 0.11.7
- **CLI extension nativescript-starter-kits:** 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Start VSCode
2. Open NativeScript Sidekick
3. Connect device via USB
4. Start LiveSync for connected device
5. App compiles and starts on device
6. I add 3 files _component_name.component.scss, component_name.component.android.scss and component_name.component.ios.scss to one of the component without existing (S)CSS and then set `styleUrls: ["./component_name.component.css"]` in component's decorator in TypeScript file
7. There seems to be some error somewhere and there is no any design for complete app
8. Stop LiveSync and remove generated files for platform in project's `/platforms` directory
9. Start the process until step 5 again and the issue is solved

I would just like to add that sometimes nativescript-dev-sass' `node-sass` package goes crazy and it uses a lot of CPU (so that the vents are activated on my MBP) until isn't manually killed from Activity Monitor. This is usually after compiling of CSS in previous step is not successful.

### Does this issue happen every time?
Yes

### Send the client logs.
I checked all logs and didn't find out anything that would be showing there's a problem with something.
 
If I was unclear at any point and you have a question, please write it down and I will try to answer as soon as possible. I will be very grateful for any information you will provide.

Thank you very much in advance!

**Comment by rosen-vladimirov** [comment] 2017-09-15 16:50
Hey @truewt ,
Thank you for the details and please excuse us for the late reply. We've investigated the case and I would like to separate the issue to two parts:
1. Newly added .scss files are not synced on device
2. Consuming a lot of CPU from `node-sass`

So let me explain each of them separately.
1. `Newly added .scss files are not synced on device`
This is a problem in the `node-sass` itself - whenever a `watch` is started, it does not watch for new files, it just watches for changes in the files that existed during starting the watch. We'll contact the authors of the `node-sass` package and see if we can introduce different behavior.
2. Consuming a lot of CPU from `node-sass`
This is a problem of starting multiple instances of `node-sass` watch processes. In fact when you use `nativescript-dev-sass` plugin and you stop LiveSync, the `node-sass` process should be killed. However, we've discovered a problem in `nativescript-dev-sass` that leaves the `node-sass` process alive. When you start another LiveSync operation a new `node-sass` process is started. So this could cause high CPU usage. The issue with leaked `node-sass` processes is fixed in latest `nativescript-dev-sass` plugin, so you can try upgrading it on your side.

Hope this clears it out.

**Comment by hettiger** [comment] 2017-10-24 08:08
@rosen-vladimirov I don't think those issues are the only ones. For me my .css files will be empty once in a while when using SideKick which is super annoying. The only way to fix this is to delete all .css files, do a platform remove android and then rebuild which triggers sass compilation again. I think something's going painfully wrong with hooks and maybe environment variables? Sidekick is really unusable if you want to use sass right now. It even causes some extra work repairing the app...

**Comment by rosen-vladimirov** [comment] 2017-11-17 10:42
Hey @hettiger , 
Please excuse me for the late reply. Can you give us more details on this case:
- which is your OS?
- which is the version of NativeScript CLI: `tns --version`
- what is the output of `tns extension` command
- steps to reproduce the issue
- `package.json` of the project where the issue occur (and `package-lock.json` in case you have such file).

**Comment by hettiger** [comment] 2017-11-17 17:55
@rosen-vladimirov It has been a while since I originally posted about that issue and therefore I can no longer provide the debugging information that you're asking for. Anyways there have been quite a few releases since then and I can't even confirm if the problem still persists. I will give Sidekick another try and make sure to give more precise feedback if I can still reproduce the described issues.

**Comment by bhavincb** [comment] 2018-03-06 19:00
when using `tns debug android` with livesync Newly added .scss files are not synced on device.
event terminating livesync and again running livesync doesn't sync new .scss file.
but if we use `tns run android` then new files added to the build.
so it seems there is issue with `tns debug android`.
please look into the issue

**Comment by ggarabedian** [comment] 2018-06-22 10:57
@hettiger, I’m going to close this issue because it has been inactive for quite some time. We were not able to reproduce the issue locally and the provided information did not contain anything specific that can explain this behavior.

Please, do not hesitate to reopen the issue if you still encounter this issue with the latest version of Sidekick, NativeScript CLI and the nativescript-dev-sass plugin. Thank you!

@bhavincb, your comment seems to be related to the NativeScript CLI and not Sidekick, nevertheless, we apologies for not answering sooner. If you continue to experience the issue with the latest version of the NativeScript CLI and the nativescript-dev-sass plugin, I would recommend that you open a new issue in the [NativeScript CLI repository](https://github.com/NativeScript/nativescript-cli/issues), because the colleagues there will be in a better position to help you.

**Closed by ggarabedian** 2018-06-22 10:57 UTC
