### ISSUE TITLE
App assets not working

### ISSUE THREAD

**Issue by delanick** [NativeScript/sidekick-feedback#139] opened 2018-03-19 18:04 UTC
I'm not able to change the app assets (icons/splashscreens) - there is no option to find and include any. Please help. Newest version of Sidekick being used.

Version: 1.7.1-v.2018.3.16.2 (latest)
NativeScript CLI version: 3.4.3
CLI extension nativescript-cloud version: 1.7.1
CLI extension nativescript-starter-kits version: 0.3.4

**Comment by bundyo** [comment] 2018-03-19 21:55
Currently the assets in Sidekick are read-only. However this feature is coming really soon - in one of the next weeks.

Closing as duplicate of #15.

**Closed by bundyo** 2018-03-19 21:55 UTC
Labels: duplicate, on roadmap
