### ISSUE TITLE
Webpack cloud build issue

### ISSUE THREAD

**Issue by mpilija** [NativeScript/sidekick-feedback#277] opened 2018-10-10 11:21 UTC
### Did you verify whether this issue has already been reported here?
No

### Tell us about the problem
We're having problems passing env variable to webpack during cloud build.

On local machine we're building using this command, and environment variable gets passed through:
tns build android --clean --release --keyStorePath C:\projects\kmgv3\KMG/Application/KMGapp/relese.keystore --keyStorePassword somesecret --key-store-alias kmg-relese --key-store-alias-password somesecret --path C:\projects\kmgv3\KMG/Application/KMGapp --bundle webpack --env.uglify --env.aot --env.snapshot --env.name=qa

When running the cloud build, this is what we're executing:
tns build cloud android --clean --release --keyStorePath C:\projects\kmgv3\KMG/Application/KMGapp/relese.keystore --keyStorePassword somesecret --key-store-alias kmg-relese --key-store-alias-password somesecret --path C:\projects\kmgv3\KMG/Application/KMGapp --bundle webpack --env.uglify --env.aot --env.snapshot --env.name=qa --accountId 1

env variable of webpack config looks like this:
![webpack](https://user-images.githubusercontent.com/25614141/46726375-7ffc8000-cc7e-11e8-97c8-ce58a93afe65.png)

Name variable contains value „true“, and it should contain „qa“. This only happens on cloud builds.
How can we pass environment variable value for the cloud build properly?

### Which platform(s) does the issue occur on?
Both
Cloud build

### Provide the following version numbers that the issue occurs with:
- **NativeScript CLI:** 4.2.3

### Tell us how to recreate the issue in as much detail as possible
Please check decription. Also, in Webpack config file, following statement has been added just to have info in log: console.log("WEBPACK:", JSON.stringify(env)); 

### Does this issue happen every time?
Yes

### Send the client logs
[build-log.txt](https://github.com/NativeScript/sidekick-feedback/files/2464424/build-log.txt)

**Comment by ggarabedian** [comment] 2018-10-10 15:24
Hello @mpilija,

Thank you for bringing this issue to our attention. The problem is caused by a bug in the NativeScript Cloud library. The fix is on a pull request and after our QA team tests it thoroughly it will be released. I will let you know as soon as the fix is available on live.

**Comment by mpilija** [comment] 2018-10-10 15:38
Thanks @ggarabedian

**Comment by ggarabedian** [comment] 2018-10-15 07:13
@mpilija, can you please update the nativescript-cloud library to its latest version (1.14.1) and let me know if the fix is working as expected on your end as well.

**Comment by mpilija** [comment] 2018-10-22 09:04
@ggarabedian we've upgraded as instructed but unfortunately, we are experiencing same issue

**Comment by ggarabedian** [comment] 2018-10-24 12:36
@mpilija, I have just tested this with the latest version of the _nativescript-cloud_ library (1.14.2) and everything appears to be working correctly. Can you please run the `tns extension` command and see what version of _nativescript-cloud_ you have installed on your machine?

**Comment by mpilija** [comment] 2018-10-24 14:30
@ggarabedian You're correct. We've double-checked installed version on our build machine and it was wrong for given user context. Everything is working now as expected. Thank you for assistance.

**Closed** 2018-11-22 13:00 UTC
