### ISSUE TITLE
NS CLI version is detected as "8.2.1"

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/sidekick-feedback#30] opened 2017-08-12 04:00 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
The version of the NativeScript CLI is reported as "8.2.1"

### Which platform(s) does the issue occur on?
N/A
Windows

### Provide the following version numbers that the issue occurs with:
[17-08-12 06:50:12.595] (Info) Version: 0.2.1-v.2017.8.8.3
[17-08-12 06:50:12.735] (Info) Checking for updates...
[17-08-12 06:50:15.496] (Info) No updates available.
[17-08-12 06:50:15.816] (Info) Loaded CLI extension nativescript-cloud, version 0.11.6.
[17-08-12 06:50:15.819] (Info) Loaded CLI extension nativescript-starter-kits, version 0.1.11.
[17-08-12 06:50:16.167] (Info) Dependencies versions: NodeJS: 8.2.1, npm: 5.3.0, NativeScript CLI: 8.2.1.
[17-08-12 06:50:16.316] (Info) Devices service initialized.

### Tell us how to recreate the issue in as much detail as possible.
When I issue `tns --version` the following text appears:

>Support for Node.js 8.2.1 is not verified. This CLI might not install or run properly.
>
>3.1.2

### Does this issue happen every time?
Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by berchik** [comment] 2017-08-13 13:35
I have a similar problem with: **NativeScript CLI: null**

"node":{"name":"NodeJS","version":"6.11.0","minVersion":"6.0.0","isMet":true},
"npm":{"name":"npm","version":"3.10.10","isMet":true},
"tns":{"name":"NativeScript CLI","version":null,"minVersion":"3.1.3","isMet":false}

Please note this started just today after I’ve updated to **NativeScript Angular v.4**

**Comment by shiv19** [comment] 2017-08-14 10:19
Hi teobugslayer,
Looks like you are using the latest "Current" version of Node.js
Switch to the Latest LTS version (v6.11.2, at the time of writing this comment)
after that, you won't see this line "Support for Node.js 8.2.1 is not verified. This CLI might not install or run properly.".
However, that line is harmless at the moment, all features of tns are working fine with
Node.js 8.2.1 as far as I have seen.

**Comment by dtopuzov** [comment] 2017-08-14 12:07
@shiv19 @berchik @teobugslayer 
`nativescript@3.1.3` officially supports `node8` so updating `nativescript` might solve the issues :)

**Comment by tsvetie** [comment] 2017-08-14 12:52
@teobugslayer, this bug is fixed in the latest version of NativeScript Sidekick, released today (v.0.2.2).
@berchik Your problem is different from the one reported here. Basically, NativeScript Sidekick requires NativeScript CLI as a prerequisite and on your machine, NativeScript Sidekick cannot detect the installed NativeScript CLI. Try the latest version of Sidekick (v.0.2.2) as it contains a couple of fixes that could solve the problem. If the update does not help you, please open a new issue with more details on your case.

**Closed** 2017-08-14 12:52 UTC
Labels: bug, fixed

**Comment by berchik** [comment] 2017-08-14 13:01
Thanks @shiv19 @tsvetie 
I can confirm that v.0.2.2 is able to locate the CLI correctly and the problem is solved
