### ISSUE TITLE
Sidekick does not recognize platform specific application Ids.

### ISSUE THREAD

**Issue by ibnYusrat** [NativeScript/sidekick-feedback#430] opened 2019-10-09 09:28 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Sidekick does not recognize platform specific application Ids and shows `[object Object]` instead of the Id.

If the application id in package.json is a string, it shows it correctly. Otherwise it does not.

And it makes sense because currently the Application ID is listed under `Properties` &rightarrow; `General` where as it _should_ be under `Properties` &rightarrow; `iOS` or `Properties` &rightarrow; `Android`. So instead of showing the ID specified in the package.json, it simply shows this:

![app_id](https://user-images.githubusercontent.com/3955226/66469189-dfaf8600-eaa0-11e9-9ee8-e03e2882d9c9.png)

And of course subsequently does not build the app. 

### Which platform(s) does the issue occur on?
Should be the same for every platform but my experience is with **Linux**. 

### Provide the following version numbers that the issue occurs with:

Version: 1.19.1-v.2019.8.1.2 (latest)
NativeScript CLI version: 6.1.2
CLI extension nativescript-cloud version: 1.18.2
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Open package.json and specify platform specific application Ids as mentioned here: https://docs.nativescript.org/tooling/changing-appid like so:
```
"nativescript": {
    "id": {
        "ios": "{appID1}" ,
        "android": "{appID2}"
    }
  }
```
2. Open the App in sidekick and look at the Application ID it shows. 

### Does this issue happen every time?
Yes

**Comment by tsonevn** [comment] 2019-10-15 12:28
Duplicate of https://github.com/NativeScript/sidekick-feedback/issues/420

**Closed by tsonevn** 2019-10-15 12:28 UTC
