### ISSUE TITLE
Trouble running on device after 5.0 upgrade

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#298] opened 2018-11-14 17:34 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I can run using the command line, but when I to to run in Sidekick I get Device errors.

### Which platform(s) does the issue occur on?
IOS

### Provide the following version numbers that the issue occurs with:

Version: 1.13.0-v.2018.10.5.2 (latest)
NativeScript CLI version: 5.0.1
CLI extension nativescript-cloud version: 1.14.4
CLI extension nativescript-starter-kits version: 0.3.5

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Click Run on Device in Nativescript Sidekick. 
2. Errors appear and app on emulator does not launch

### Does this issue happen every time?
Yes

### Send the client logs
IOs
class2tns
Send Feedback
Getting Started
Brad (Tom Torres)
Back to My Apps
Show Files
Terminal
Open in Editor
New Page
Build
Publish
Devices
Properties
Plugins
Assets
Services
CONNECTED DEVICES
iPhone XR (Emulator)
    
Nexus 7 API 26 Oreo (Emulator)
    
Build Type
Local 
 Cloud 

Build Configuration
Debug 
 Release 

Webpack
  

Start Debugger
    
  

All

Errors 4

Device Console
[18-11-14 11:49:17.899] Unable to connect for 10000ms, Error: Unable to connect for 10000ms
    at Timeout._onTimeout (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/helpers.js:417:46)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[18-11-14 11:49:17.923] (CLI) (node:8291) UnhandledPromiseRejectionWarning: Error: Cannot connect to device socket. The error message is Unable to connect for 10000ms
    at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:135:21)
    at SocketProxyFactory.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)
    at emitWarning (internal/process/promises.js:81:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:8291) Error: Cannot connect to device socket. The error message is Unable to connect for 10000ms
    at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:135:21)
    at SocketProxyFactory.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)
(node:8291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:95:13)
    at emitWarning (internal/process/promises.js:88:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
[18-11-14 12:20:51.689] Unable to connect for 10000ms, Error: Unable to connect for 10000ms
    at Timeout._onTimeout (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/helpers.js:417:46)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[18-11-14 12:20:51.706] (CLI) (node:8291) UnhandledPromiseRejectionWarning: Error: Cannot connect to device socket. The error message is Unable to connect for 10000ms
    at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:135:21)
    at SocketProxyFactory.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)
    at emitWarning (internal/process/promises.js:81:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:8291) Error: Cannot connect to device socket. The error message is Unable to connect for 10000ms
    at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:135:21)
    at SocketProxyFactory.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)

[console_18-11-14_11-45-45.003.log](https://github.com/NativeScript/sidekick-feedback/files/2581881/console_18-11-14_11-45-45.003.log)

 
iOS

**Comment by ggarabedian** [comment] 2018-11-19 07:00
Hello @bradrice,

The only way in which I was able to reproduce the reported error is by manually closing the app on the emulated device and then selecting `Run on Device` with debugger enabled. Currently, this behavior is expected because when the app is installed on the device, but closed, we cannot launch it and the debugger doesn't have anything to attach to, which results in a timeout error. Please, let me know if you encounter the same issue, or the steps you take to reach it are different.

Having said that, we are looking for ways to make this possible in Sidekick, because as you have mentioned, this scenario is working as expected in the NativeScript CLI. For the time being, the only workaround we can suggest is to start the app manually and then attach the debugger.

I hope this is of any help.

**Comment by darkyelox** [comment] 2018-12-21 02:00
I have this problem too, but running from VSCode using launch option for debug.

**Comment by NickIliev** [comment] 2019-03-13 08:27
@darkyelox please if possible open a new issue [here](https://github.com/NativeScript/nativescript-cli/issues?utf8=%E2%9C%93&q=Android+app+bundle) for the issue related to debugging in VSCode with launch option. Closing this issue as the main case has an applicable workaround provided above.

**Closed by NickIliev** 2019-03-13 08:27 UTC
Labels: ios
