### ISSUE TITLE
Sidekick debugger on Windows 10 panels not working.

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#125] opened 2018-01-30 16:22 UTC
I’ve tried to get Sidekick working with debugger. I am able to console.log from my app, but for some reason I can’t get the elements panel to show the elements of my app running in an android emulator. Is this possible? I’m building locally and selecting start debugger.

I'm on Windows 10 and I've also tried debugging on a device instead of in an emulator.

I'm just running the tutorial Groceries app
 
Debugger output when I launch:

ActivityManager: Start proc org.nativescript.Groceries for activity org.nativescript.Groceries/com.tns.NativeScriptActivity: pid=22893 uid=10373 gids={50373, 9997, 1028, 1015, 3003} abi=armeabi-v7a
ActivityManager: Permission Denial: getCurrentUser() from pid=22893, uid=10373 requires android.permission.INTERACT_ACROSS_USERS
ActivityManager: Permission Denial: getCurrentUser() from pid=22893, uid=10373 requires android.permission.INTERACT_ACROSS_USERS
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.

**Comment by Plamen5kov** [comment] 2018-01-31 07:19
Hi @bradrice,
Can you fill out the issue template, because there are a couple of questions there, that will help us figure out your problem. Thank you! Exact steps to reproduce would be great, along with the versions of all the packages you're using.

**Comment by Plamen5kov** [comment] 2018-01-31 11:37
@bradrice,
Once the dev tools window opens up and loads all it's resources:
* Press `F1`
* Press `Restore defaults and reload`
* Navigate to the Elements tab, and see if you can see them.

I guess it's some kind of a timing issue, but we'll have to investigate further.

**Comment by bradrice** [comment] 2018-01-31 13:30
# Please, provide the details below:
Sorry, I didn't provide my issue in the proper format. I've redone it here. I appreciate the help.

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
This may not only be related to Sidekick as I have also tried running the build from the command line and then copying the url into the debugger and I still don't get the Elements panel to work.

### Which platform(s) does the issue occur on?
I run Windows 10 version 1709

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
Version: 1.2.1-v.2018.1.25.3 (latest)
- **NativeScript CLI:** 
NativeScript CLI version: 3.4.1
- **CLI extension nativescript-cloud:** 
CLI extension nativescript-cloud version: 1.3.0
- **CLI extension nativescript-starter-kits:** 
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Click Open App 
2. Click Run on Device selecting Debug and Start Debugger
3. Chrome Debugger - Console works, Sources seems to show the right assets. Elements does not show anything.

### Does this issue happen every time?
Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
https://gist.github.com/bradrice/69048a975e0ef27a2c5e9ca5cb40099a

 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by ggarabedian** [comment] 2018-06-26 12:21
Hello @bradrice,

Apologies for not addressing this issue for so long. 

Thank you for sharing the Sidekick logs, unfortunately, they do not contain any additional information about the issue at hand. I hope that the new versions of the NativeScript CLI and Sidekick resolved this problem and you are able to access and use the Elements tab successfully while debugging. 

With the above in mind, I will now close this issue as it is quite old. Please, feel free to reopen it if the issue is still reproducible on your side and you would like us to investigate this further.

Thank you!

**Closed by ggarabedian** 2018-06-26 12:21 UTC
