### ISSUE TITLE
App Name 

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/sidekick-feedback#366] opened 2019-04-09 13:34 UTC
I realise this has been posted before, but .....

Please please please allow us to change the App Name in Sidekick away from the Folder name. I have to create copies of projects as they are developed but the old versions are still valid and need updating with new Provisioning and certificates as they are Enterprise Apps. Because I have to use a backup folder name to keep the history the subsequent compiled app takes the new name of the folder, so so inconvenient. I have to back up the latest project, rename the old project to the original folder name and re-compile which is a real pain. Why can't we have an App Name and a Source folder if this detail is critical to the compiled app.

**Comment by tsonevn** [comment] 2019-04-10 05:28
Duplicate of https://github.com/NativeScript/sidekick-feedback/issues/85

**Closed by tsonevn** 2019-04-10 05:28 UTC
