### ISSUE TITLE
Error text in output doesn't wrap.

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/sidekick-feedback#287] opened 2018-10-24 18:04 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When I tried to run on my device, an error was reported, however, the text didn't wrap and I couldn't read the error. I had to click the Copy to Clipboard option, paste in another editor, just to read it.

Here is a screen shot - note the red text doesn't wrap.

![image](https://user-images.githubusercontent.com/393660/47451405-469f3680-d78d-11e8-9467-abac929d1e6e.png)

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:

Version: 1.13.0-v.2018.10.5.2 (latest)
NativeScript CLI version: 4.2.4
CLI extension nativescript-cloud version: 1.14.2
CLI extension nativescript-starter-kits version: 0.3.5

### Does this issue happen every time?
Not sure

**Comment by bundyo** [comment] 2018-10-24 18:39
Thanks for the report, but it is a duplicate of #178.

The problem is that currently due to high amount of output, the console is virtualized and virtualization doesn't work very well with variable height items. There is a title on that row, so you can read it if you hover over it for a moment. That said, there still is ongoing work to fix that problem as is visible from issue #178.

I'm closing this as duplicate.

**Closed by bundyo** 2018-10-24 18:39 UTC
