### ISSUE TITLE
A UI Pro plugin fork has crept in

### ISSUE THREAD

**Issue by Izrab** [NativeScript/sidekick-feedback#410] opened 2019-07-31 14:41 UTC
### Did you verify whether this issue has already been reported here?
No

### Tell us about the problem
In the past, when we navigated to plugins page to install some plugins, by default, the Pro UI plugins were appearing like a useful advertisement, but it has been a while, a guy named `UI Autocomplete Ex` has crept into the rows of the genuine UI Pro plugins. 
And, when when clicked on it, that warning message appears immediately.
![Annotation 2019-07-31 172827](https://user-images.githubusercontent.com/22328131/62221402-71df3380-b366-11e9-8de0-d88fa742d669.png)

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:
![image](https://user-images.githubusercontent.com/22328131/62221551-aa7f0d00-b366-11e9-8c2b-480c89ce30e8.png)

### Does this issue happen every time?
_Yes

**Comment by tsonevn** [comment] 2019-08-01 04:43
HI @Izrab,
I've checked the described case, however, was unable to recreate a similar problem. Restart the SideKick app and check again if you will have the same issue. Also, make sure that you are using latest {N} CLI and {N} versions.

**Comment by Izrab** [comment] 2019-08-01 06:57
@tsonevn , Indeed I'm using latest {N} CLI and {N} versions and latest {N} Sidekick, at this moment of speaking.

**Comment by tsonevn** [comment] 2019-08-01 09:27
HI @Izrab,
I've discussed the issue with the dev team and confirm that this is a valid problem. Also,  this issue(#410) seems to be duplicated with #409 and #408. On that matter, I will link the issue here and #409 in issue #408 and will mark them as duplicate.
Duplicate of #408

**Closed by tsonevn** 2019-08-01 09:27 UTC

**Comment by Izrab** [comment] 2019-08-01 12:56
@tsonevn , Thanks for developing Sidekick, I love it.
