### ISSUE TITLE
Windows Installation required administrator access

### ISSUE THREAD

**Issue by shiv19** [NativeScript/sidekick-feedback#34] opened 2017-08-14 10:14 UTC
I wanted to report that when I tried installing Sidekick on my windows machine
without administrator access, it installed a Sidekick in which I was not able to see
any starter templates. When I created a project in it, it created it with the "42 Taps"
starter template.

After that, I tried installing sidekick with **Administrator** access. And then, everything 
installed correctly, and I was able to see all the starter templates made available via
Sidekick.

OS: Windows 8.1 Single Language
NativeScript: v3.1.3

**Comment by tsvetie** [comment] 2017-08-14 14:27
@shiv19 Could you attach the log files? You can find them in:

Windows: %AppData%\NativeScriptSidekick\Logs
macOS: ~/Library/Application Support/NativeScriptSidekick/Logs
Linux: ~/.config/NativeScriptSidekick/Logs

Additionally, how were you able to create an app with Sidekick if you did not see any templates?

**Comment by shiv19** [comment] 2017-08-15 06:16
[Logs.zip](https://github.com/NativeScript/sidekick-feedback/files/1224278/Logs.zip)
Here is the logs folder.

@tsvetie 
It just showed create app button. couldn't select project type as well.

but anyways it is working fine now... 😄

**Comment by shiv19** [comment] 2017-08-21 10:39
@bundyo 
I've provided the information that was asked.

**Comment by bundyo** [comment] 2017-08-21 10:48
Yes, nothing to do with you - we still didn't reproduce it and it requires more attention on our side.

**Comment by ggarabedian** [comment] 2018-06-22 10:00
Hello @shiv19,

This issue is quite old and we are going to close it.

The provided logs (by the way, thank you for sharing those) did not contain any information that can explain this behavior. Our tests did not turn out anything either and we were not able to reproduce the problem locally. We assume that the issue is related to the Windows 8.1 OS, but then again, we were not able to reproduce it when testing on the specified OS version. 

Having said that, we have exhausted all options based on the provided information. If you continue to experience the problem and believe that the issue needs to be reopened, please do so. :)

**Closed by ggarabedian** 2018-06-22 10:00 UTC
Labels: need more information
