### ISSUE TITLE
Option to upload app icons?

### ISSUE THREAD

**Issue by Spatlani** [NativeScript/sidekick-feedback#40] opened 2017-08-22 20:24 UTC
I am unable to find any option to update my app icons from the assets tab. It shows the existing icons but to change them I have to go through each separate directory and change the files. It will make more sense if there is a simple option to upload a single icon file which can be changed to their respective resolutions?

**Comment by bundyo** [comment] 2017-08-23 05:22
Duplicate of #15

**Closed by bundyo** 2017-08-23 05:22 UTC
Labels: duplicate, feature
