### ISSUE TITLE
App froze after clicking on Assets tab, other tabs not opening.

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/sidekick-feedback#17] opened 2017-08-02 14:10 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
The app froze while changing settings, once I navigated to the Assets tab it got stuck on the Assets tab and can't move to other tabs. 
**More over the assets shown in the tab were not added by me and they do not belong in this project, they belong to my already existing project.**

### Which platform(s) does the issue occur on?
macOS - 10.12.6 (16G29)

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

Version: 0.2.0-v.2017.7.31.4 (latest)
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Created a new project
2. Was changing the settings for different platforms
3. Clicked on Assets Tab
4. App frozen - Couldn't navigate to other tabs
5. Assets shown in the asset tab were not added by me
6. Assets shown belong to an existing project.

### Does this issue happen every time?
No

### Send the client logs.
_The client logs can help us identify what is causing the issue. 
[Archive.zip](https://github.com/NativeScript/sidekick-feedback/files/1194144/Archive.zip)

Video for reference:

[2017-08-02 09-55-28.mp4.zip](https://github.com/NativeScript/sidekick-feedback/files/1194145/2017-08-02.09-55-28.mp4.zip)

**Comment by ventsislav-georgiev** [comment] 2017-08-07 14:08
@sudhanshu-15 Thank you for the report. 

It seems from the video that the UI is in an erroneous state. Unfortunately, the logs did not contain any useful information and we found an issue in which we do not log the UI errors. The fix for the logs will be available in the next release and if/when this happens again, then the logs can provide more insights on the erroneous state of the UI.

**Comment by bundyo** [comment] 2017-08-14 09:44
We released an update last Wednesday that included UI logging improvements, did you stumble upon this issue since the update and if you did, can you provide the logs again? 

Thanks in advance.

**Comment by sudhanshu-15** [comment] 2017-08-14 14:57
@bundyo @ventsislav-georgiev I did an update today and tried to replicate the issue, the app did not freeze this time. But I noticed that when I switch between projects, the Asset tab takes a couple of seconds before loading the other project assets.

On a side note I also got a error notification which reads: 
```
[17-08-14 10:51:45.430] (Error) Source: event handler for "select" Message: Cannot read property 'value' of undefined, TypeError: Source: event handler for "select" Message: Cannot read property 'value' of undefined
    at a.onSelectRow (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:17242:46)
    at n (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:534:1169)
    at a.e (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:534:6233)
    at a.t.$emit (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:534:59016)
    at a.removeSelection (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:16330:30)
    at a.n [as removeSelection] (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:534:1181)
    at a.selectRow (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:16339:26)
    at a.n [as selectRow] (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:534:1169)
    at a.$nextTick (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:16366:45)
    at Array.<anonymous> (file:///Applications/NativeScript%20Sidekick.app/Contents/Resources/app.asar/ui/app.js:534:52034)

```
Not sure if this is a related issue or a new one. If you want I can create a new issue for this.

**Comment by bundyo** [comment] 2017-08-14 17:42
No, it happens when you try to select the Android orientation and has already been reported today. Fix is on its way.

**Comment by tsvetie** [comment] 2017-08-16 08:48
Closing as the issue is no longer reproducible.

**Closed by tsvetie** 2017-08-16 08:48 UTC
Labels: need more information
