### ISSUE TITLE
iOS cloud build runs for hours

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/sidekick-feedback#326] opened 2019-01-10 05:47 UTC
@theremon commented on [Wed Jan 09 2019](https://github.com/NativeScript/NativeScript/issues/6778)

**Environment**
Windows 10 Pro build 1803 
 - CLI: 
Component nativescript has 5.1.0 version and is up to date.
 - Cross-platform modules:
Component tns-android has 5.1.0 version and is up to date.
Component tns-ios has 5.1.0 version and is up to date.
 - Plugin(s):

**Describe the bug**
Got an application that is building fine locally on Android. It has been installed on Android devices etc and everything is ok. When trying through Sidekick to use iOS Cloud Build in order to create and test the same application on an iPhone, after creating the certificates etc, the procedure runs for many hours, with no apparent result. In some attempts, timeout errors from amazon-aws were received, in others nothing - it's just extremely slow with no feedback. In the Windows Task Manager, during all this time there are Java processes, some VirtualBox processes, NodeJS processes that get spawned and killed by Sidekick along with the Sidekick ones.
Previous attempts worked ok and we have had successful tests with other apps or older versions of the app, completing in just a few minutes.

In the latest run, everything was uploaded in about 2 minutes. After that, it the Build Step started. After 1 hour and 50 minutes, the message 'Checking for updates...' appeared. It now has been another 2 hours and nothing has happened yet.

If you need any further information that can be publicly shown without exposing the project, please ask.

Any advice would be greatly appreciated.
Thanks everyone...

package.json contents:
{
  "nativescript": {
    "id": "org.nativescript.MyClient",
    "v8Flags": "--expose_gc",
    "tns-android": {
      "version": "5.1.0"
    },
    "tns-ios": {
      "version": "5.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "nativescript-angular": "~7.0.0",
    "nativescript-oauth2": "^1.1.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-snackbar": "^4.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-zxing": "^1.5.7",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.3.3",
    "tns-core-modules": "^5.1.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.0.0",
    "@nativescript/schematics": "~0.4.0",
    "@ngtools/webpack": "7.1.3",
    "nativescript-dev-typescript": "0.7.8",
    "nativescript-dev-webpack": "0.18.4",
    "typescript": "^3.1.6"
  },
  "readme": "NativeScript Application"
}

---

@sepccom commented on [Wed Jan 09 2019](https://github.com/NativeScript/NativeScript/issues/6778#issuecomment-452732673)

My Nativescript Typescript is also stalling during an IOS Cloud Build. Here is the VS Output Log if this helps. An urgent fix would be helpful. Thanks.

1>------ Build started: Project: PunchList, Configuration: Debug iOS Cloud ------
1>Please wait while we prepare your project. This might take some time.
1>Getting accounts information...
1>Using account 30281662-c5fb-4a4b-a9ce-7ea346d1609f.
1>Starting cloud build of 'C:\Users\awday\Source\Repos\PunchList\PunchList', platform: 'iOS', configuration: 'Debug', buildId: 541a9ffa-4dae-4a1c-8fb2-2e9f433c3058.
1>Prepare step started.
1>Executing before-shouldPrepare hook from C:\Users\awday\Source\Repos\PunchList\PunchList\hooks\before-shouldPrepare\nativescript-dev-webpack.js
1>Skipping prepare.
1>Prepare step completed.
1>Upload step started.
1>Upload step completed.
1>Build step started.
1>  ios Build Tooling revision 2018.12.11.1 origin/release-v2
1>  Build Tooling Hostname administrators-mac-177.local
1> App package not specified. Skipping unzip step.
1>  NativeScript CLI version 5.0.3
1> Add platform ios with runtime version 5.0.0
1>Copying template files...
1>Platform ios successfully added. v5.0.0
1> Prepare Project for Platform -  ios

**Comment by ggarabedian** [comment] 2019-01-10 09:05
Hello @theremon and @sepccom, 

Thank you for reporting this unexpected behavior. It seems that we were experiencing a sporadic issue with one of the services in our cloud infrastructure. We are still investigating what might have caused the problem. 

Having said that, if you try to build your apps now, the process should complete successfully. Can you please give it a try and share the outcome?

**Comment by theremon** [comment] 2019-01-10 13:49
Hello again

thanks for the update.
I'm still facing the same issue - I had to stop Sidekick after a long time.
However, an interesting bit of new info is that after creating a new application and copying the code over without any changes, the project compiles and gets installed on the iPhone properly.
There are still some settings that need to be made in order to have two identical projects, but so far the new project seems to be working. It's not normal however to have to recreate projects all the time in order to get them to compile. It'd be best if the issue was identified...

**Comment by sepccom** [comment] 2019-01-12 13:50
Hi guys, Just wondering if anyone has been able to see what the issue is? I think building an IOS project to the device is primary to Nativescript. Not sure why this issue isn't getting the attention it deserves.

**Comment by ggarabedian** [comment] 2019-01-14 09:03
We are currently not able to reproduce the issue on our side, which is a prerequisite to debug it and determine what might be causing the problem. We are not certain if the issue is related to the cloud infrastructure or to temporary connectivity problems.

@theremon, it's strange to hear that creating a new project and copying the files in it resolves the issue. This might imply that the data is getting corrupted at some point. Have you tried to rebuild the original project and does it still express the same behavior?

@sepccom, I would like to note that the Sidekick extension for Visual Studio 2017 is no longer actively developed. The public preview showed us that the demand for such extension is not high enough to justify the development effort. This is noted by our Product Manager in this [post](https://github.com/NativeScript/sidekick-feedback/issues/294#issuecomment-442527921). Nevertheless, I conducted several tests with a newly created project in Visual Studio 2017 and I was able to build successfully in every attempt, so the issue doesn't seem to be related to the extension. 

We will continue to investigate the problem and attempt to reproduce it on our end. I'll let you know as soon as we have made any progress or have additional information.

**Comment by ChaseXC** [comment] 2019-07-01 21:49
NativeScript CLI Version: 5.4.2
ios runtime version: 5.2.0

I just wanted to say that I have run into this issue twice, and both times happened after I tried to run multiple cloud builds sequentially, where the first few have failed on me at some point during the process for other reasons. An example of one of the failures I encountered was a missing TypeScript interface definition that was being used somewhere in my project at the time I had ran the cloud build. After resolving all of the errors, I just get stuck at the exact same line: "Prepare Project for Platform - ios". The first time this happened, it cleared itself after some amount of time (I can't remember how long exactly... a day? Or a weekend maybe?) and I was able to do successful builds after that. This leads me to believe there is maybe some caching issue that is stopping me from building after one of my unsuccessful builds. The second time I have run into this build problem was today, after some more unsuccessful cloud builds (due to other issues, which, again, were resolved). I tried running the "Clean Cloud Workspace" command from NS Sidekick, expecting that to possibly help, but it did not. Not sure when the cloud builds will start working for me again, I will get back to this thread when they do.

Let me know if any more information would help.

**Comment by ChaseXC** [comment] 2019-07-11 20:38
I think I may have found a viable workaround: I close out of NativeScript Sidekick, recursively delete the ~/.config/NativeScriptSidekick directory, and then start up Sidekick again. After doing so, my ios cloud build seems to work just fine. I suspect the workaround that @theremon found, where they created a new project and copied over the files, only worked because the cache values found in the ~/.config/NativeScriptSidekick directory were essentially reset by using a new project.

It would be nice if anyone else having this problem could confirm whether my solution works or not.

**Closed** 2019-09-30 06:17 UTC
Labels: ios, need more information
