### ISSUE TITLE
no resolver registered for projectService

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/sidekick-feedback#79] opened 2017-11-03 13:35 UTC
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I have a local copy of [the {N}adidas sample app](https://github.com/tjvantoll/nadidas). When I open it in Sidekick and click the “View App” button I get the following error.

```
[17-11-03 09:24:06.842] (Error) no resolver registered for projectService, Error: no resolver registered for projectService
    at Yok.resolveByName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:321:27)
    at Yok.resolve (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:262:25)
    at Yok.resolveInstance (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:106:34)
    at Object.get (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:98:22)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-app-service.js:19:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[17-11-03 09:24:12.975] (Error) no resolver registered for projectService, Error: no resolver registered for projectService
    at Yok.resolveByName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:321:27)
    at Yok.resolve (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:262:25)
    at Yok.resolveInstance (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:106:34)
    at Object.get (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:98:22)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-app-service.js:19:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[17-11-03 09:28:37.425] (Error) Communication with the child process was ended. Errors: /usr/local/lib/node_modules/nativescript/lib/common/yok.js:321
                    throw new Error("no resolver registered for " + name);
                    ^

Error: no resolver registered for iOSDeviceProductNameMapper
    at Yok.resolveByName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:321:27)
    at Yok.resolve (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:262:25)
    at ctor.$inject.args.map.paramName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:292:29)
    at Array.map (native)
    at Yok.resolveConstructor (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:287:48)
    at Yok.resolve (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:259:25)
    at IOSDeviceDiscovery.createAndAddDevice (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/ios-device-discovery.js:46:39)
    at $iosDeviceOperations.startLookingForDevices (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/ios-device-discovery.js:38:26)
    at IOSDeviceLibStdioHandler.wrappedDeviceFoundCallback (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-device-operations.js:53:28)
    at emitOne (events.js:96:13)
    at IOSDeviceLibStdioHandler.emit (events.js:188:7)
```

### Which platform(s) does the issue occur on?
macOS 10.12.6

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** Version: 0.2.7-v.2017.10.26.3 (latest)
- **NativeScript CLI:** 3.3.0
- **CLI extension nativescript-cloud:** 0.16.0
- **CLI extension nativescript-starter-kits:** 0.3.1

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application.
2. Open a local clone of the [{N}adidas sample](https://github.com/tjvantoll/nadidas).
3. Click “View App” on the {N}adidas app in Sidekick.

### Does this issue happen every time?
Yes

### Send the client logs.
https://gist.github.com/tjvantoll/6111157a6319bf2c3a7b67354d4ae2f1

**Comment by berchik** [comment] 2017-11-04 13:29
same error in win10

**Comment by tsvetie** [comment] 2017-11-06 12:47
Hello guys,

Most probably, you have hit one of our known issues - I noticed that you are using npm 5.4.2. In case you are using npm 5.4.0, 5.4.1 or 5.4.2, you will not be able to create a project from template, that has dependency to nativescript-telerik-ui. The problem is in npm itself - it is unable to create project when more than one package has `preinstall` script. 

Unfortunately, the only workaround that we can suggest until the fix makes it into npm, is to use an older version of npm.

**Comment by tsvetie** [comment] 2017-11-06 12:49
Possible duplicate of #44

**Closed** 2018-03-27 15:39 UTC
